version: "3.8"
name: sketchy-dex
volumes:
  db_data:

services:
  postgres:
    image: postgres:15
    container_name: container_pg
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    ports:
      - 4000:8080